#include "types.h"

#define CADRE_VGA_TOP (CNN_VGA_H-CNN_IMAGE_IN_H)/2
#define CADRE_VGA_BOTTOM CNN_VGA_H-CADRE_VGA_TOP
#define CADRE_VGA_LEFT (CNN_VGA_W-CNN_IMAGE_IN_W)/2)
#define CADRE_VGA_RIGHT CNN_VGA_W - CADRE_VGA_LEFT

void overlay(char label,CNN_IMAGE_TYPE imageIn[CNN_IMAGE_IN_SIZE],CNN_IMAGE_TYPE imageOut[CNN_VGA_SIZE]);
