


#define IMGPROC_A_PS 20, 10, true, AC_RND
#define IMGPROC_IMAGE_IN_SIZE_0 320
#define IMGPROC_IMAGE_IN_SIZE_1 240
#define IMGPROC_IMAGE_IN_SIZE_2 3
#define IMGPROC_IMAGE_IN_P 20, 10, true, AC_RND
#define IMGPROC_IMAGE_IN_SIZE IMGPROC_IMAGE_IN_SIZE_0*IMGPROC_IMAGE_IN_SIZE_1*IMGPROC_IMAGE_IN_SIZE_2

#define IMGPROC_IMAGE_OUT_SIZE_0 320
#define IMGPROC_IMAGE_OUT_SIZE_1 240
#define IMGPROC_IMAGE_OUT_SIZE_2 64
#define IMGPROC_IMAGE_OUT_P 20, 10, true, AC_RND
#define IMGPROC_IMAGE_OUT_SIZE IMGPROC_IMAGE_OUT_SIZE_0*IMGPROC_IMAGE_OUT_SIZE_1*IMGPROC_IMAGE_OUT_SIZE_2

#define IMGPROC_KERNEL_SIZE_0 320
#define IMGPROC_KERNEL_SIZE_1 240
#define IMGPROC_KERNEL_P 20, 10, true, AC_RND
#define IMGPROC_KERNEL_SIZE IMGPROC_KERNEL_SIZE_0*IMGPROC_KERNEL_SIZE_1*IMGPROC_IMAGE_OUT_SIZE_2*IMGPROC_IMAGE_IN_SIZE_2
