#ifndef __IMGPROC_VFIX__
#define __IMGPROC_VFIX__


#define IMGPROC_A_PS 20, 10, true, AC_RND
#define IMGPROC_IMAGE_IN_H 24
#define IMGPROC_IMAGE_IN_W 24
#define IMGPROC_IMAGE_IN_C 3
#define IMGPROC_IMAGE_IN_P 20, 10, true, AC_RND
#define IMGPROC_IMAGE_IN_SIZE IMGPROC_IMAGE_IN_H*IMGPROC_IMAGE_IN_W*IMGPROC_IMAGE_IN_C

#define IMGPROC_IMAGE_OUT_H 24
#define IMGPROC_IMAGE_OUT_W 24
#define IMGPROC_IMAGE_OUT_C 64
#define IMGPROC_IMAGE_OUT_P 20, 10, true, AC_RND
#define IMGPROC_IMAGE_OUT_SIZE IMGPROC_IMAGE_OUT_H*IMGPROC_IMAGE_OUT_W*IMGPROC_IMAGE_OUT_C

#define IMGPROC_KERNEL_H 3
#define IMGPROC_KERNEL_W 3
#define IMGPROC_KERNEL_P 20, 10, true, AC_RND
#define IMGPROC_KERNEL_SIZE IMGPROC_KERNEL_H*IMGPROC_KERNEL_W*IMGPROC_IMAGE_OUT_C*IMGPROC_IMAGE_IN_C

#endif
